[search]
device_family = "iphone_air"
models = [
    "MG2L4X/A",  # 256GB Space Black
    "MG2M4X/A",  # 256GB Cloud White
    "MG2N4X/A",  # 256GB Light Gold
    "MG2P4X/A",  # 256GB Sky Blue
    "MG2Q4X/A",  # 512GB Space Black
    "MG2U4X/A",  # 512GB Light Gold
    "MG2V4X/A",  # 512GB Sky Blue
    "MG2T4X/A",  # 512GB Cloud White
    "MG2W4X/A",  # 1TB Space Black
    "MG2X4X/A",  # 1TB Cloud White
    "MG2Y4X/A",  # 1TB Light Gold
    "MG304X/A"   # 1TB Sky Blue
]
carriers = []
country_code = "my"
zip_code = "55188"
stores = ["R742"]

[general]
polling_interval_seconds = 120
report_after_n_counts = 30
data_path = "data.csv"
log_path = "log.txt"
randomize_proxies = false

[telegram]
username = "@rekki0"
api_id = "24628242"
api_hash = "4bfe5c5fcf3047a89128402e89fe0193"
bot_token = "8465465163:AAESrhxsx_aU3DmJIb_LYLJUduJwpYnVMP8"
session_name = "iPhoneAirFinder"
group_id = "-1003191053710" # e.g. -1001234567890
topic_key = "iphone_air"
topics = { iphone_air = 5 } # replace 0 with the forum topic ID
