[search]
device_family = "iphone_17_pro"
models = [
    "MG8G4X/A", # 256GB Silver
    "MG8H4X/A", # 256GB Cosmic Orange
    "MG8J4X/A", # 256GB Deep Blue
    "MG8K4X/A", # 512GB Silver
    "MG8M4X/A", # 512GB Cosmic Orange
    "MG8N4X/A", # 512GB Deep Blue
    "MG8P4X/A", # 1TB Silver
    "MG8Q4X/A", # 1TB Cosmic Orange
    "MG8R4X/A"  # 1TB Deep Blue
]
carriers = []
country_code = "my"
zip_code = "55188"
stores = ["R742"]

[general]
polling_interval_seconds = 120
report_after_n_counts = 30
data_path = "data_iphone17_pro.csv"
log_path = "log_iphone17_pro.txt"
randomize_proxies = false

[telegram]
username = "@rekki0"
api_id = "24628242"
api_hash = "4bfe5c5fcf3047a89128402e89fe0193"
bot_token = "8465465163:AAESrhxsx_aU3DmJIb_LYLJUduJwpYnVMP8"
session_name = "iPhone17ProFinder"
group_id = "-1003191053710"
topic_key = "iphone_17_pro"
topics = { iphone_air = 5, iphone_17 = 2, iphone_17_pro = 3, iphone_17_pro_max = 4 }
